<a href="https://colab.research.google.com/github/kerrygoaround/ML100Days/blob/main/D01_NumPy_%E5%A5%97%E4%BB%B6%E5%9F%BA%E6%9C%AC%E6%93%8D%E4%BD%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import numpy as np
np.__version__

'1.19.5'

In [13]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
a=np.arange(21)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [16]:
#2.呈上題，將以上數列取出偶數。
b=np.arange(2,21,2)
print(b)

[ 2  4  6  8 10 12 14 16 18 20]


In [17]:
#3.呈1題，將數列取出3的倍數。
c=np.arange(3,21,3)
print(c)

[ 3  6  9 12 15 18]
